In [24]:
print(r'c:\n\n\n')# print raw string no interpretetion

c:\n\n\n


In [25]:
10

10

In [26]:
_ + 5  #(_ is for output of previous operation)
    

15

In [27]:
a= "hello"
print(a[1:10]) # if we are giving last subscript greater.. no issues.. willwork

ello


In [28]:
l = [1,5,7,8,4,6]
print(l)
del l[1:3]
print(l)

[1, 5, 7, 8, 4, 6]
[1, 8, 4, 6]


In [29]:
# Set uses the hash concept for storing values

In [33]:
# Dictionary
key = [1,2,3]
values = ['a','b','c']
dic = dict(zip(key,values))
print(dic)
print(dic.get(1))
print(dic.get(4)) # if key not present no error, if you use, dic[4].... error.. this is dic with key =4
print(dic.get(4,'Not Found'))
print(dic.get(1,'Not Found'))

dic = {1:'a',2:['a','b','c'],3:{1:'a',2:'b'}}
print(dic)
print(dic[2][1:3])
print(dic[3][2])

{1: 'a', 2: 'b', 3: 'c'}
a
None
Not Found
a
{1: 'a', 2: ['a', 'b', 'c'], 3: {1: 'a', 2: 'b'}}
['b', 'c']
b


In [34]:
# setting path
#1. use command prompt 'setpath' ..but that is for that cmd session only
#2. Go to env variables add new and give the path where python is installed


In [35]:
a = 10
print(id(a))
b = a
print(id(b))
c = 10
print(id(c))
print(id(10))
# all same
# Garbage collector... when a variable is derefrenced then the address is ready for garbage collector

140726310057072
140726310057072
140726310057072
140726310057072


In [36]:
# data types
'''
1. None.. variable with assigned value
2. Numeric
 a. int
 b. flaot
 c. complex ...a= 6+7j
 d. bool
3. Sequence types
  a.list
  b. set
  c. tuple
  d. range ... print(list(range(10)))... print 0-9.. to get the values.. use list function
  e. string
4. Dictoinary

'''

'\n1. None.. variable with assigned value\n2. Numeric\n a. int\n b. flaot\n c. complex ...a= 6+7j\n d. bool\n3. Sequence types\n  a.list\n  b. set\n  c. tuple\n  d. range ... print(list(range(10)))... print 0-9.. to get the values.. use list function\n  e. string\n4. Dictoinary\n\n'

In [38]:
# Number system conversion
n  = 20
print(bin(20))
print(oct(20))
print(hex(20))
n= 0o24
print(n)

0b10100
0o24
0x14
20


In [39]:
'''
# bit wise operators
1. ^ xor
2. ~ 2's complement
3. & AND
4. | OR
'''


"\n# bit wise operators\n1. ^ xor\n2. ~ 2's complement\n3. & AND\n4. | OR\n"

In [40]:
'''
Run file 
1. Using IDLE...
    a.) File... New File... Save and run
    b.) Use notepad...save in .py
2. Using cmd
    a.) Go to the library.... use python filename
3. IDE ... Debugging option is there as well


'''

'\nRun file \n1. Using IDLE...\n    a.) File... New File... Save and run\n    b.) Use notepad...save in .py\n2. Using cmd\n    a.) Go to the library.... use python filename\n3. IDE ... Debugging option is there as well\n\n'

In [42]:
'''
#input from user
1. Input()
2. eval(input()).... evaluate a expression ... 2+6-1
3. argv....0 is file name... 1 onwards are arguments...all in string format
''' 
import sys
print(sys.argv[0])

C:\Users\Garg\Anaconda3\lib\site-packages\ipykernel_launcher.py


In [43]:
# indentation ..by default 4 spaces.. 1 tab

In [44]:
# usage of pass... used for no instructions
def a():
    pass
class x:
    pass
x = int(input("Enter a number"))
if x %2==0:
    pass
else:
    print("Odd Number")


Enter a number 4


In [46]:
# for else in python

l1 = [1,2,3,4]
for i in l1:
    if i % 5==0:
        print("Hello")
        break            # manadtory for "For else"
else:
    print("No condition were executed in for loop")

No condition were executed in for loop


In [10]:
# Array in python
from array import *
arr = array('i',[1,2,3,4,5])
print(arr.typecode)
'''
Different types of Typecode
b -- int signed
B -- int unsigned
u -- unicode 
f -- float 4
d -- double 8
'''
print(arr.buffer_info(),"Buffer info")  # address and size
print(len(arr),"Length")
arr.reverse()
print(arr,"array reversed")
for i in arr:
    print(i)
arr1 = array(arr.typecode,[a for a in arr])
print(arr1)
arr1.append(7)
print(arr1,"Value appended 7")
print(arr1.index(7),"Index of 7")

i
(1015694673696, 5) Buffer info
5 Length
array('i', [5, 4, 3, 2, 1]) array reversed
5
4
3
2
1
array('i', [5, 4, 3, 2, 1])
array('i', [5, 4, 3, 2, 1, 7]) Value appended 7
5 Index of 7


In [4]:
# Multidim array
'''
use numpy
pip ---pip install package
'''
from numpy import *
# creating arrays
a1 = array([1,2,3,4,5])
a2 = arange(1,15,2) # stepwise like range functiokn
a3 = zeros(5) # returns float
a4 = ones(5) # returns float
a5 = linspace(1,40,11) # break 1n 11 parts from 1-40...by default part is 50
a6 = logspace(1,40,5) # break in 5 parts..10 raise to 1 to 10 raise to 40
print(f"a1 {a1}")
print(f"a2 {a2}")
print(f"a3 {a3}")
print(f"a4 {a4}")
print(f"a5 {a5}")
print(f"a6 {a6}")
print('%.2f' %a6[0])

# properties
print("Properties")
print(f"a1.size {a1.size}")
print(f"a1.dtype {a1.dtype}")
print(f"a1.ndim {a1.ndim}")
print(f"a1.shape {a1.shape}")

#Copy array
print("Copy array,info is commented out")
'''
1. just referencing  a1 = a2 ... same address
2. shallow copy  a2 = a1.view() ...different address but if one changed both changed
3. deep copy .... a2 = a1.copy() ... different address.. one changes another doesn't change
'''

#Matrix
a7 = arange(1,25,1)
print(a7.reshape(4,6),"Reshaped into 2D")
print(a7.reshape(3,4,2),"Reshaped into 3d")
print(a7.flatten(),"converted to 1D")
print(a7.reshape(3,4,2))
m = matrix(a7)
print(m, "Printing matrix")
m1  = matrix('1 2 5;3 4 8;5 6 9') # cols seprated by semicolon and cols by space
m2  = matrix('1 2 5;3 4 8;5 6 9')
print(m1+m2,"Adding of matrix")
print(m1*m2,"Multiplication")
print(diagonal(m1),"diagonal of matrix")
print(m1.max(),"Max of m1")
print(cos(m1))

a1 [1 2 3 4 5]
a2 [ 1  3  5  7  9 11 13]
a3 [0. 0. 0. 0. 0.]
a4 [1. 1. 1. 1. 1.]
a5 [ 1.   4.9  8.8 12.7 16.6 20.5 24.4 28.3 32.2 36.1 40. ]
a6 [1.00000000e+01 5.62341325e+10 3.16227766e+20 1.77827941e+30
 1.00000000e+40]
10.00
Properties
a1.size 5
a1.dtype int32
a1.ndim 1
a1.shape (5,)
Copy array,info is commented out
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]] Reshaped into 2D
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]] Reshaped into 3d
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] converted to 1D
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]] Printing matrix
[[ 2  4 10]
 [ 6  8 16]
 [10 12 18]] Adding of matrix
[[ 32  40  66]
 [ 55  70 119]
 [ 68  88 154]] Multiplication
[1 4 9] dia

In [55]:
'''
This(3 quotes) is always used for documentation, dont use it for comments 
'''

'\nThis(3 quotes) is always used for documentation, dont use it for comments \n'

In [56]:
'''
compiled language is a one where compiler converts your code to machine language
1. python ---> code-->compiler-->bytecode--->PYM(Python virtual machine) ---> machine code
2. PYM --> required for code portability

python types
1. cpython ....python implemented in c
1. jpython ....python implemented in java
1. ironpython ....python implemented in .dot net
'''

'\ncompiled language is a one where compiler converts your code to machine language\n1. python ---> code-->compiler-->bytecode--->PYM(Python virtual machine) ---> machine code\n2. PYM --> required for code portability\n\npython types\n1. cpython ....python implemented in c\n1. jpython ....python implemented in java\n1. ironpython ....python implemented in .dot net\n'

In [63]:
l1 = [1,2,3]
l2 = ['a','b','c']
z1 = zip(l1,l2) # zip 2 lists
for a,b in z1:
    print(a,b)
l3 = list(zip(l1,l2))
s1 = set(zip(l1,l2))
d1 = dict(zip(l1,l2))
print(l3)
print(s1)
print(d1)


1 a
2 b
3 c
[(1, 'a'), (2, 'b'), (3, 'c')]
{(3, 'c'), (1, 'a'), (2, 'b')}
{1: 'a', 2: 'b', 3: 'c'}
